### ISSUE TITLE
请问这个现在还更新吗?

### ISSUE THREAD

**Issue by zanderzhg** [gnsilence/JPGZService#1]
请问这个现在还更新吗?

**Comment by gnsilence** [comment]
> 请问这个现在还更新吗?

这个不更新了，有时间会再传一个版本，
http://49.233.174.240:44357
admin  Admin123...
这个是前后台分离，后台就是这个项目的.net core 3.1版本

**Comment by zanderzhg** [comment]
> > 请问这个现在还更新吗?
> 
> 这个不更新了，有时间会再传一个版本，
> http://49.233.174.240:44357
> admin Admin123...
> 这个是前后台分离，后台就是这个项目的.net core 3.1版本

收到.谢谢.
